### ISSUE TITLE
Getting feature extent in Openlayers.

### ISSUE THREAD

**Issue by JonnyBGod** [cutting-room-floor/wax#110]
I believe this is possible with the mm boxselector.

But would it be possible to retrieve the clicked feature's shape or even better its extent?

The ideas is to enable a click/zoom to extent functionality in my service.

Thanks in advanced.

**Comment by tmcw** [comment]
Hey,

I'm not sure what you're trying to achieve here - are you using UTFGrid (and `wax.ol.interaction`)? The UTFGrid spec doesn't pass over actual feature geometries or extents - you'd need to add that to your datasource, whether calculated automatically in a PostGIS query or added manually to a Shapefile or such.

**Comment by tmcw** [comment]
Hey @JonnyBGod - any more details? Really struggling to figure out your intent enough to answer this question.

**Comment by JonnyBGod** [comment]
Hey @tmcw,

your first comment was relevant to the matter.

The Idea is to use UTFGrid and TileStream to stream the polygons and/or the features extent/bounds to the client.

I believe this would be a nice temporary solution for my idea wich is to draw the polygons on mouse hover and zoom in on mouse click.

I understand that for this I will have to add an extra column to the shapefile with the polygons for each row.

Do you have any insight on the better way to do it?
I have a lot of rows so it would be good to know of an automation to do it.

Another issue is the best way to deliver the polygons, I was thinking on going GeoJSON. Any insight on this?

Thanks.

**Comment by tmcw** [comment]
> The Idea is to use UTFGrid and TileStream to stream the polygons and/or the features extent/bounds to the client.
> I believe this would be a nice temporary solution for my idea wich is to draw the polygons on mouse hover and zoom in on mouse click.

There are plenty of initial tests of this, but it's really very strongly not recommended. If you're planning on drawing polygons, you'll need to implement at least two different vector drawing methods, and then deal with the rather awful performance of browsers rendering vectors. And, on top of that, the size of polygons in your data - which are typically very, very large and 'simplification' of them will cause them not to match up with the underlying map.

Delivering the polygons is rather simple, but the rest of the situation is pretty awful, and that's why we don't support it.

If your intent is to zoom to polygons, you should put the bounding boxes in your data. If you want to highlight polygons, it's recommended to either change your spec so that you don't need to, because the technology isn't there yet.

**Comment by JonnyBGod** [comment]
You analysis seams fair with my experience. I will leave the highlighting to the end as an experiment and try to figure out another way to lead the users to zoom in and click.

Would you know a way to add this new column to the shapefile with the boundaries for each feature?

For the sake of experimentation would it be possible to highlight the UTFGrid features?
This would be a nice way to do it instead of the polygons. Just calculating similar pixels and draw them.

**Comment by tmcw** [comment]
JonnyBGod: might want to look in QGIS or ArcGIS walkthroughs (whatever you're using) for that sort of thing. Sometimes geometry calculators provide it, otherwise you'll need to code it.

It's possible to highlight pixels - we've done a few experiments in that area, and it 'works', but obviously is a bit of a hack.

**Comment by JonnyBGod** [comment]
Great I think I could build the interface I need around the grid.

Could you point me on the right direction on how to achieve the grid pixels highlighting?

I was looking to try a bit of hacking around GridManager...

**Comment by tmcw** [comment]
Yeah, pretty much you can access grid data through methods on `GridInstance`, and then start searching around the grid for all blocks of the same key. A naïve approach is usually okay for this, but your highlighting will stop at tile boundaries, so you'll need to fix that annoying problem.

**Comment by tmcw** [comment]
Okay, closing here; open a new ticket for specific concerns or open a ticket on the specific project.
