### ISSUE TITLE
Wax Manual / Examples - Is this it?

### ISSUE THREAD

**Issue by ns-1m** [cutting-room-floor/wax#126]
If you are looking for examples for wax, It seems that that is this the manual

http://mapbox.com/wax/

Is this manual?

It seems harder to read and use than the documentation of  Leaflet and OpenLayers. It shows snippet but not a complete code at the end to download and try. I thought that the wax simplies Leaflet, OL, etc.

However, probably wax is not intended to be used if you are just starting to learn OpenLayers and Leaflet.

**Comment by tmcw** [comment]
Hi Noli,

The 'snippets' of code in the Wax manual are complete and you can happily copy & paste them as you wish. They are literally the code that runs the map, so if it works on the page, it'll work on your page. aka, it is the complete code.

Wax does not simplify or wrap anything; read [Scope and Limitations](http://mapbox.com/wax/wax-scope.html), which describes what it does aim to do.

If you're trying to learn OpenLayers or Leaflet, you don't need to learn Wax, and would be better of reading the Leaflet or OpenLayers docs; this much should be pretty obvious. If you find that you need Wax - for fast map configuration with TileJSON, more controls for Modest Maps, or interactivity with UTFGrid, you'll need it, and the docs should be of assistance.

As far as 'harder to read and use', perhaps I'm biased because I wrote them, but if you have any specific improvements in mind, the website is [a branch of the project](https://github.com/mapbox/wax/tree/gh-pages), open source and freely licensed, that you can edit and contribute back to. I'd greatly appreciate that, because it's very hard to address non-specific problems.
