### ISSUE TITLE
"Uncaught ReferenceError: dragEnd is not defined"

### ISSUE THREAD

**Issue by palewire** [cutting-room-floor/wax#267]
Getting this in my console when using the trunk wax.leaflef.js. Not sure if it's breaking the experience at all, but it seems like something worth noting.

**Comment by springmeyer** [comment]
Looking at [recent commits](https://github.com/mapbox/wax/commits/master/control/lib/interaction.js) it appears this just broke in master due to a missing:

``` js
    function dragEnd() {
        _downLock = false;
    }
```

The above code can be seen being added in 8b7ded168d418b0abdaddcdadc837518793a8252, but goes missing when merged in cefe4aa40395eab0923a0604f0c099c4c4c81c83.

/cc @tmcw
