### ISSUE TITLE
OpenLayers Example - Interactive Layers

### ISSUE THREAD

**Issue by robotastic** [cutting-room-floor/wax#35]
There seems to be a lack of documentation on how to use openlayers with Wax. All of the examples in the manual are for ModestMaps or Google Maps. I looked back at the /examples directory that used to be part of Wax, but it focused on Records based maps. Are there some simple examples out there of how to put together a Wax based OpenLayers map? 

I am using a base layer and then an interactivity overlay on top of that. It looks like I need to use OpenLayers for that because ModestMaps only support a single layer. I have built the docs using Docco, but they don't provide too much insight. 

Thanks for any pointers you can offer!

**Comment by tmcw** [comment]
Yep, there's definitely a need to document OpenLayers, and I've only done the sweep over Modest Maps, because it's just a lot simpler than OL (less holes to fall down, less API crud).

It's definitely possible to have multiple layers in Modest Maps, albeit through a bit of a hack: making two maps on top of each other and having the one reposition whenever the other one does.

Adding interaction with OpenLayers should be as simple as adding a `new wax.ol.Interaction()` control to your map, which will find all eligible layers (those created with TMS), and give you the fundamental level of interaction.

**Comment by robotastic** [comment]
No worries at all, this stuff rocks... and I know I am out in Dragons Lie Here territory. The Modest Maps tip is great though. I just mashed two layers together and it worked fine. Weird! 

I will have to give the Openlayers approach a try sometime, but ModestMaps stacking seems to work pretty good and has less bloat.

Thanks!

Here is the code in case others need it:

```
<div class='section'>
<div id='modestmaps-interaction' class='map'>
</div>
 <script type='text/javascript'>
var mm = com.modestmaps;
var m = new mm.Map('modestmaps-interaction',
    new com.modestmaps.WaxProvider({
      baseUrl: 'http://localhost:8888/',
      layerName: 'dc-light3'}), new mm.Point(800,400))
  .interaction();
m.setCenterZoom(
  new com.modestmaps.Location(39, -77),
  12);

var l = new mm.Map('modestmaps-interaction',
    new com.modestmaps.WaxProvider({
      baseUrl: 'http://localhost:8888/',
      layerName: 'dc-interactive'}), new mm.Point(800,400))
  .interaction();
l.setCenterZoom(
  new com.modestmaps.Location(39, -77),
  12);
</script>
</div>
```

**Comment by noahg** [comment]
I'd like to use OpenLayers with Wax because I want to

a) use a Google baselayer
b) use a transparency control on an overlaid tile layer
3) use Wax to display UTFgrid tooltips for that overlaid layer. 

I've gotten the ol-connector example working, I'm having a tough time figure out how to then load multiple layers, and how to load a mb-util exported mbtiles tms layer without using TileJSON. Any guidance would be much appreciated!
