### ISSUE TITLE
Tooltips for overlapping/clustered interaction

### ISSUE THREAD

**Issue by robotastic** [cutting-room-floor/wax#39]
I am not quite sure at what layer this issue lies (TileMill, Stream or Wax). It doesn't look like the toolchain can handle interactivity layers where there are multiple points and the same location. An example would be 3 points at the same addresses, you would want information for all 3 points returned when moused over. Is this currently possible and I am doing this wrong? Is special coding need for the Wax tooltips when you have multiple points?

The ideal behavior would be that you would get all of the items displayed with you mouse over a point and all of the detailed information for all of the points when you click.

**Comment by tmcw** [comment]
This currently isn't the way that the stack behaves:

Mapnik, the renderer at the core, outputs grid data for the points that appear on a map. In a final step, it removes any points that don't actually appear - like those that are too small to be represented by a pixel or those that are covered up by other points. So, you're interacting with only the top layer of the rendered data, not the data itself.

At this point, this means that clustering points needs to be done ahead of time, and you can do whatever data combination you want in the code you use for clustering, and any parsing and presenting of that data in formatters.

Down the line, when Mapnik supports pluggable data processors in the rendering engine, it'll be more possible to cluster data within itself, but this'll be after a bunch of refactoring, since it isn't something that belongs in Mapnik core.

**Comment by robotastic** [comment]
Thanks!
That is what I was suspecting. I will work on consolidating points with the same address, so that at a very zoomed in view a user could at least access all of the data.
