### ISSUE TITLE
Sizing issues with Leaflet interaction control under Webkit

### ISSUE THREAD

**Issue by mourner** [cutting-room-floor/wax#61]
Chrome stable doesn't size wax tooltips in Leaflet correctly. It seems that it forgets to redraw the block after img gets its size. You need to try one of Webkit force redraw workarounds, or try adding the image to the tooltip on img load.

**Comment by tmcw** [comment]
I've noticed another problem with the Leaflet section - scrolling down, when you just hit the top of the Leaflet maps, they each show up in an exaggerated size. Here's a screenshot for the effect: http://d.pr/Jb9H

Not sure if this is my bleeding-edge Chrome (13.0.782.15 dev) or something in the page layout / positioning that's causing this problem, or a feature of Leaflet?

**Comment by mourner** [comment]
I noticed this on bleeding edge Chrome too, but I'm sure this will be fixed as it's OK in the Chrome stable. Probably Chrome edge doesn't update overflow:hidden tiles clipping immediately while scrolling.

**Comment by tmcw** [comment]
Cool.

For the time being, I'm not seeing a great workaround here. The most viable option seems to be writing a quick version of a onload handler that can run on a `<div>`, finding all elements with `onload` events and firing when all are completed, but it seems like a lot of code instead of simply asking users to define explicit sizes for image elements. Tooltip content is totally freeform, so there'll be more complex cases than this one - most likely extra content being loaded in async, and the responsibility should be on tooltip authors, I think.

**Comment by mourner** [comment]
Hmm, but if it's not a control implementation issue, I don't get why Modest Maps and Open Layers interaction control works as expected without clipping. There must be some difference in creating the tooltip between the libraries.

**Comment by tmcw** [comment]
It might be the element that the tooltip is sitting inside that's causing the browsers to treat them differently - tooltip creation is in [tooltip.js](https://github.com/mapbox/wax/blob/master/control/lib/tooltip.js), which is used by all of the APIs, and the only difference between them is the `context` parameter, which is the element the tooltip is placed under.

**Comment by mourner** [comment]
Weird, I'll try to figure this out when I have a spare minute.

**Comment by mourner** [comment]
BTW, regarding the Chrome issue with tiles sticking out of container: here's a bug I submitted for this: http://code.google.com/p/chromium/issues/detail?id=86299

**Comment by tmcw** [comment]
Okay, let's track this upstream, in Chrome and/or Leaflet - nothing I can really see as actionable in this project.
