### ISSUE TITLE
Hover/Click Element Controls

### ISSUE THREAD

**Issue by netconstructor** [cutting-room-floor/wax#71]
I am hoping this capability currently exists and is just not documented yet but I can't seem to find references or any information on being able to create/control or customize the style of map feature elements.

If I understand things correctly here (this is the solution I was looking into)... The TileMill application controls the rendering of all datasets used to create static raster tiles and thus if one wanted to add (for example) parcel shapefiles to a custom designed map then tilemill is utilized to style these shapefiles, define when and how they are displayed (based on zoom levels) and is then in charged of processing these files into raster images. These images are then delivered to the end users through tilestream based upon queries preformed from the end users browser by means of "WAX" being the script/code that specifically calls tiles and deals with end user interaction/control of the map.... ok, that was kinda a long blabbing

Anyway... From all the info and examples I have read over the past 4 hours I was quite excited to get started in attempting to shift to the above outlined solutions in an effort to completely replace tools like google/yahoo or bing. What I have failed to find any information on is any type of native polygon shape creation, styling or hover/click action capabilities.

By utilizing google I have the ability to load a shapefile / kml or geojson data directly or execute a query to a postgis db based upon map coordinate values, turn the resulting data into polygons which are displayed over the map. More importantly, I am able to style each polygon individually so I can for example highlight one or more previously selected parcels and/or control the exact hover and desired actions based upon such polygon values.

Now, with Wax I "think" I am SOL if I require such functionality naively so I want to know if my assumptions are indeed correct or if I am missing something here?

My biggest concern in attempting this switch is that it is just not built for these needs and therefor attempting to hack together a solid/robust solution will in end effect not scale in terms of the size of polygon and/or point data.

The main thing which has me writing this ticket is that I just can't wrap my head around the fact that such controls don't exist as I feel such interactivity controls are critical and must have been considered on your firms end. As far as I can tell when TileMill creates the tiles they can and do have some types of geo data referenced within them and some examples showcased specific center-lined "lat/long points" for rendered polygon map layers. I believe each of those points could even be selected and hold values to be displayed upon a click/hover... but again, no references to custom polygon layers/shapes.

From my research it seems that the best solution available to provide such interactivity (specifically when visualizing large polygon/point files) is Google's fusion tables solution.

Please tell me that you have SOME type of interim solution which addresses these concerns and/or any current plans which take such needs into serious consideration.

Assuming this is not on the roadmap, does WAX naively support the capability of just calling these layers utilizing the same techniques Google makes available through their API?

Thanks for your time,

Chris

**Comment by tmcw** [comment]
Hey,

Well, your initial understanding of the Wax/TileMill/TileStream interaction is pretty much perfectly on key, so you've got that :).(just one point - Wax itself uses Modest Maps, OpenLayers, Leaflet, or Google Maps for actual tiling interface)

So as far as what you're looking for:

Wax has as one of its main features the ability to interact with polygons (or points, etc) on maps that come from TileMill. It does this by reading rasterized data that's sent along with tiles - data that includes the pixels that are interactive, but not the original shapes. The current state of the library makes maps interactive, but does not restyle them based on this.

> The main thing which has me writing this ticket is that I just can't wrap my head around the fact that such controls don't exist as I feel such interactivity controls are critical and must have been considered on your firms end.

Heh, well...

There's a much longer story to this, but the essential parts are:
- TileStream is currently possible to deploy and keep online because it's not a live rendering server. All it does is provide you with tiles and interactivity data generated by TileMill, and do that quickly. When we do switch to a live rendering server (in my mind, an eventuality), then this will become much more possible.
- Vector rendering in-browser is a deathtrap for all but the fastest of browsers. Google is able to pull this off because they can build a separate rendering stack for every browser in question, and then build a backend rendering interface for those browsers that would never perform acceptably (IE). Wax and its tools work on all browsers (and don't include ks of lines of code) by avoiding all in-browser vector rendering.
- Styling such feature in-browser would also require a styling language that ports across platforms - something that we're working on with a browserification of Carto, but that is not close to finishing, and is several steps ahead of what most sweet mapping frameworks are thinking about.
- Believe it or not, interactivity with kajillions of features that look good and work in a relatively infinitely-flexible way is enough for most clients :)

If hover effects on-map - changing the color of a polygon when it's clicked, or adding a border to it - are a make it-or-break it feature for you, Google's your best bet. If you can cut out IE, try Polymaps.

Otherwise, try just installing TileMill - it's free, obviously, and will give you a much better idea of the scope of the tools.

**Comment by netconstructor** [comment]
Thank you very much for your detailed and rapid response.

In terms of your remarks let me ask a few brief additional questions to ensure I have a complete picture here.

1) I have experimented googles fusion tables in terms of displaying an interactive layer and it seems their tool truly delivers upon its promise including the ability to apply polygon hovering capabilities from realtime queries. My question - have you experimented with this, what are your thoughts on such implementations and would it be possible to natively apply such a layer utilizing your tools?

2) You mention polymaps which I have looked into briefly but not in depth. Have you guy run any tests in terms of its performance and ability to render live polygon data from a database? Are their any other alternatives to them which might work better?

3) So, in terms of the objectives of the project I am attempting to find the perfect solution for I wanted to do the following:
- a) Utilize TileMill to create/render a slick custom basemap layer with deep zoom layers and elevation topography through transparent pngs.
- b) As part of the tilemill create/rendering process I may pass some default point values so tiles at certain zoom levels may have some point values for fixed locations such as shopping malls, banks, restaurants... and display such info through tooltips.
- c) I would create additional static transparent layer tiles through tilemill which would be displayed on top basemap which could be turned on/off by the user - for example heatmaps displaying sales activity in the last 30, 60, 90, 180 days. I would setup this process so tilemill would run on a cron to automatically create new tiles at set intervals based on data available in a specific directory on the server.
- d) I would utilize your tools to display the default baselayer map and allow for the user interaction of turning on/off layers. 

Up to this point I believe this approach represents the best way of doing things and as long as all map data is hosted in a location such as amazon ec2 or your systems the performance of these maps should scale without question and without any license restrictions coming into play compared to utilizing bing/googles solutions.

Now... If you don't mind - please take a moment and visit this link: http://www.zillow.com/homes/92101_rb/

What you will notice when viewing the map above is that they are rendering two additional sets of data onto the map namely polygones for areas along with map markers. You should notice that these elements seem to render very quickly.

So, based on your recommendation, what would be the best way to achieve a solution similar to this as a layer on top of the map with hovering capabilities?

Finally, what you will notice on the link above is that at that zoom level the markers are not legible and should be presented in clusters. So, in your opinion what solution would be best to provide such clustering capabilities. Essentially... if two or more points are within "x" distance from each other then group them. I am assuming the best way would be to render such cluster values in the json at the server level depending upon the zoom level as well as through javascript on the browsers end. This would in turn mean that if a deep zoom lets say two markers would be within "x" distance to the point where they would overlap they are clustered otherwise are just presented normally.

If I remember correctly the google maps API has such capabilities but what approach is best when utilizing your solution?

Thanks in advance for your response,

Christian Hochfilzer

**Comment by tmcw** [comment]
> My question - have you experimented with this, what are your thoughts on such implementations and would it be possible to natively apply such a layer utilizing your tools?

Yes, see the Wax manual: we support overlays on top of Google maps. Though I haven't mucked around in the Fusion Tables API and have no idea whether that'd work.

> You mention polymaps which I have looked into briefly but not in depth. Have you guy run any tests in terms of its performance and ability to render live polygon data from a database?

Polymaps is a level above that - you'd need to use TileStache or something similar to actually pull data from a database. To do this you'd have to cut IE support, and my best guess is that it would not be performant.

> What you will notice when viewing the map above is that they are rendering two additional sets of data onto the map namely polygones for areas along with map markers. You should notice that these elements seem to render very quickly.

That's because Zillow is using Flash: if you want to take that bitter pill, then it is indeed quite easy to do polygon hovering.

> So, based on your recommendation, what would be the best way to achieve a solution similar to this as a layer on top of the map with hovering capabilities?

As before, either Fusion tables, Flash, or cutting the feature from the site, with an emphasis on the last one.

> If I remember correctly the google maps API has such capabilities but what approach is best when utilizing your solution?

Mapnik has label collision avoidance and I believe Polymaps has clustering as an example. But given the uncertain behavior of how clusters are presented and what they do, we haven't pushed much in that area.

**Comment by netconstructor** [comment]
thanks
